# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Lint
on:
  pull_request: null
  push:
    branches:
    - trunk
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  actionlint:
    name: Actionlint
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run actionlint
        uses: docker://rhysd/actionlint:latest
        with:
          args: "-color -verbose -shellcheck="

  octoscan:
    name: Octoscan
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Checkout Octoscan
      uses: actions/checkout@v4
      with:
        repository: synacktiv/octoscan
        path: octoscan

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Install dependencies
      run: go mod tidy

    - name: Build Octoscan
      run: go build

    - name: Run Octoscan
      run: ./octoscan/octoscan scan .
