# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Lint workflow files
on:
  pull_request:
    paths:
      # Only run when changes are made to workflow files.
      - '.github/workflows/**'
  push:
    branches:
      - trunk
    paths:
      # Only run when changes are made to workflow files.
      - '.github/workflows/**'
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    permissions:
      security-events: write
      actions: read
      contents: read
    uses: ./.github/workflows/reusable-workflow-lint.yml
