# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Deploy Assets
on:
  workflow_call:
    inputs:
      plugin:
        required: true
        type: string
        description: The plugin slug
      readme:
        required: true
        type: string
        description: The plugin readme file name, either readme.md or readme.txt
    secrets:
      WPORG_SVN_USERNAME:
        required: true
      WPORG_SVN_PASSWORD:
        required: true

permissions: {}

jobs:
  wordpress:
    name: WordPress.org
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false

      - name: Populate Changelog
        uses: johnbillion/plugin-infrastructure/.github/actions/populate-changelog@trunk
        id: changelog
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Readme
        run: | #shell
          echo "${CHANGELOG}" > "${README}"
        env:
          CHANGELOG: ${{ steps.changelog.outputs.changelog }}
          README: ${{ inputs.readme }}

      - name: Commit
        run: | #shell
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -m "Assets"

      - name: Install SVN
        run: | #shell
          sudo apt-get update
          sudo apt-get install -y subversion
          svn --version

      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-asset-update@4eb612e1fceb9425cd6286a166ba1a4210052f64 # 2.1.3
        env:
          README_NAME: ${{ inputs.readme }}
          IGNORE_OTHER_FILES: true
          SVN_USERNAME: ${{ secrets.WPORG_SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.WPORG_SVN_PASSWORD }}
