# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Deploy Tag
on:
  workflow_call:
    inputs:
      plugin:
        required: true
        type: string
        description: The plugin slug
      readme:
        required: true
        type: string
        description: The plugin readme file name, either readme.md or readme.txt
      deploy:
        required: true
        type: boolean
        description: Whether to deploy the release to WordPress.org
      version:
        required: true
        type: string
        description: The version number of the release
    secrets:
      WPORG_SVN_USERNAME:
        required: true
      WPORG_SVN_PASSWORD:
        required: true
    outputs:
      zip-path:
        description: The path to the generated zip file
        value: ${{ jobs.wordpress.outputs.zip-path }}
      version:
        description: The version number of the release
        value: ${{ inputs.version }}

permissions: {}

jobs:
  wordpress:
    name: WordPress.org
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    timeout-minutes: 10
    outputs:
      zip-path: ${{ steps.deploy.outputs.zip-path }}
    environment:
      name: WordPress.org
      url: "https://wordpress.org/plugins/${{ inputs.plugin }}/"
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.version }}
        persist-credentials: false

    - name: Populate Changelog
      uses: actions/github-script@v7
      env:
        FILENAME: ${{ inputs.readme }}
      with:
        script: | #js
          const fs = require('fs');
          const { FILENAME } = process.env
          const { data: releases } = await github.rest.repos.listReleases( context.repo );

          let published = releases.filter( release =>
            ! release.draft && ! release.prerelease
          );

          let sorted = published.sort( ( a, b ) =>
            new Date( b.published_at ) - new Date( a.published_at )
          );

          let changelog = sorted.map( ( release ) => {
            const date = new Date( release.published_at ).toLocaleDateString(
              'en-gb',
              {
                year: 'numeric',
                month: 'long',
                day: 'numeric',
              }
            );

            return [
              `### ${release.tag_name} (${date}) ###`,
              '',
              `${release.body}`,
            ].join('\n');
          } );

          // Show a maximum of 10 releases
          changelog = changelog.slice( 0, 10 );

          changelog.push(
            '### Earlier versions ###',
            `For the changelog of earlier versions, <a href="https://github.com/${context.repo.owner}/${context.repo.repo}/releases">please refer to the releases page on GitHub</a>.`,
          );
          changelog.unshift('## Changelog ##');

          // Append the changelog
          try {
            fs.appendFileSync( FILENAME, '\n' + changelog.join( '\n\n' ) );
          } catch ( exception ) {
            console.error( exception );
            process.exitCode = 1;
          }

    - name: Commit Changelog
      run: | #shell
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add "${README}"
        git commit -m "Readme"
      env:
        README: ${{ inputs.readme }}

    - name: Install SVN
      run: | #shell
        sudo apt-get update
        sudo apt-get install -y subversion
        svn --version

    - name: WordPress Plugin Deploy
      uses: 10up/action-wordpress-plugin-deploy@2.2.2
      id: deploy
      env:
        SVN_USERNAME: ${{ secrets.WPORG_SVN_USERNAME }}
        SVN_PASSWORD: ${{ secrets.WPORG_SVN_PASSWORD }}
        VERSION: ${{ inputs.version }}
      with:
        dry-run: ${{ ! inputs.deploy }}
        generate-zip: true

    - name: Upload zip
      uses: actions/upload-artifact@v4
      with:
        name: deployed-${{ inputs.plugin }}-${{ inputs.version }}
        path: ${{ steps.deploy.outputs.zip-path }}

  github:
    name: GitHub Milestones
    if: ${{ inputs.deploy }}
    runs-on: ubuntu-24.04
    permissions:
      issues: write
    timeout-minutes: 10
    steps:
    - name: Get next versions
      id: semvers
      uses: WyriHaximus/github-action-next-semvers@v1.2.1
      with:
        version: ${{ inputs.version }}

    - name: Create next patch milestone
      run: gh api "/repos/${GITHUB_REPOSITORY}/milestones" --field "title=${TITLE}" || true
      env:
        GITHUB_TOKEN: ${{ github.token }}
        TITLE: ${{ steps.semvers.outputs.patch }}

    - name: Create next minor milestone
      run: gh api "/repos/${GITHUB_REPOSITORY}/milestones" --field "title=${TITLE}" || true
      env:
        GITHUB_TOKEN: ${{ github.token }}
        TITLE: ${{ steps.semvers.outputs.minor }}

    - name: Create next major milestone
      run: gh api "/repos/${GITHUB_REPOSITORY}/milestones" --field "title=${TITLE}" || true
      env:
        GITHUB_TOKEN: ${{ github.token }}
        TITLE: ${{ steps.semvers.outputs.major }}

    - name: Close completed milestone
      run: | #shell
        JQ_FILTER='.[] | select(.title == "'"${WP_VERSION}"'") | .number'
        ID="$(gh api "/repos/${GITHUB_REPOSITORY}/milestones" --jq "$JQ_FILTER")"
        if [ -n "$ID" ]; then
          gh api "/repos/${GITHUB_REPOSITORY}/milestones/${ID}" --method "PATCH" --field "state=closed"
        fi
      env:
        GITHUB_TOKEN: ${{ github.token }}
        WP_VERSION: ${{ inputs.version }}
