# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Acceptance Tests
on:
  workflow_call:
    inputs:
      wp:
        required: true
        type: string
        description: WordPress version to use in major.minor format (e.g. 6.4), or "latest" or "nightly"
      php:
        required: true
        type: string
        description: PHP version to use in major.minor format (e.g. 8.0)
      node:
        required: true
        type: boolean
        description: Whether to run the Node build step

permissions: {}

jobs:
  test:
    name: PHP ${{ inputs.php }}
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    timeout-minutes: 10
    env:
      LOCAL_PHP: ${{ inputs.php }}
      LOCAL_WP_DEBUG: ${{ inputs.php < 8.1 && 1 || 0 }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Configure environment variables
      run: | #shell
        echo PHP_FPM_UID="$(id -u)" >> "$GITHUB_ENV"
        echo PHP_FPM_GID="$(id -g)" >> "$GITHUB_ENV"

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.0
        tools: composer:v2
        coverage: none
        ini-file: development
      env:
        fail-fast: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Get Composer cache directory
      id: composer-cache
      run: echo dir="$(composer config cache-files-dir)" >> "$GITHUB_OUTPUT"

    - name: Composer cache
      uses: actions/cache@v4
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: composer-8.0-${{ hashFiles('composer.json') }}

    - name: Install Composer dependencies
      run: | #shell
        if [ "${WP_VERSION}" == "latest" ]; then
          composer install --dev --prefer-dist
        elif [ "${WP_VERSION}" == "nightly" ]; then
          composer require --dev --prefer-dist --update-with-dependencies roots/wordpress-full="dev-main"
        elif [[ "${WP_VERSION}" =~ ^[0-9]\.[0-9]$ ]]; then
          composer require --dev --prefer-dist --update-with-dependencies roots/wordpress-full="~${WP_VERSION}.0"
        else
          composer require --dev --prefer-dist --update-with-dependencies roots/wordpress-full="${WP_VERSION}"
        fi
      env:
        WP_VERSION: ${{ inputs.wp }}

    - name: Setup node
      if: ${{ inputs.node }}
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
        cache: npm

    - name: Install node dependencies
      if: ${{ inputs.node }}
      run: npm ci

    - name: Run the build
      if: ${{ inputs.node }}
      run: npm run build

    - name: Start Docker environment
      run: composer run test:start -- --quiet-pull

    - name: Log WordPress version
      run: docker compose run --rm wpcli core version

    - name: Run the tests
      run: composer run test:acceptance

    - name: Upload test artifacts
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: acceptance-wp-${{ inputs.wp }}-php-${{ inputs.php }}
        path: tests/_output

  timeline:
    name: Generate workflow timeline
    runs-on: ubuntu-24.04
    permissions: {}
    timeout-minutes: 10
    needs:
      - test
    steps:
    - name: Generate workflow timeline
      uses: Kesin11/actions-timeline@v2.2.1
      with:
        show-waiting-runner: false
