# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Static Analysis
on:
  workflow_call:
    inputs:
      php:
        required: true
        type: string
        description: PHP version to use in major.minor format (e.g. 8.0)

permissions: {}

jobs:
  test:
    name: ${{ inputs.php }}
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    timeout-minutes: 10
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php }}
        tools: composer:v2
        coverage: none
        ini-file: development
      env:
        fail-fast: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Get Composer cache directory
      id: composer-cache
      run: echo dir="$(composer config cache-files-dir)" >> "$GITHUB_OUTPUT"

    - name: Composer cache
      uses: actions/cache@v4
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: composer-${{ inputs.php }}-${{ hashFiles('composer.json') }}

    - name: PHPStan cache
      uses: actions/cache@v4
      with:
        path: tests/cache/phpstan
        key: phpstan-${{ inputs.php }}-${{ hashFiles('composer.json') }}-${{ hashFiles('phpstan.neon.dist') }}

    - name: Install dependencies
      run: composer install

    - name: Run static analysis
      run: composer test:phpstan
