# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Integration Tests
on:
  workflow_call:
    inputs:
      wp:
        required: true
        type: string
        description: WordPress version to use in major.minor format (e.g. 6.4), or "latest" or "nightly"
      php:
        required: true
        type: string
        description: PHP version to use in major.minor format (e.g. 8.0)
      node:
        required: true
        type: boolean
        description: Whether to run the Node build step

permissions: {}

jobs:
  test:
    name: PHP ${{ inputs.php }}
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    timeout-minutes: 10
    env:
      LOCAL_PHP: ${{ inputs.php }}
      LOCAL_WP_DEBUG: ${{ inputs.php < 8.1 && 1 || 0 }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with:
        persist-credentials: false

    - name: Configure environment variables
      run: | #shell
        echo PHP_FPM_UID="$(id -u)" >> "$GITHUB_ENV"
        echo PHP_FPM_GID="$(id -g)" >> "$GITHUB_ENV"

    - name: Install PHP
      uses: shivammathur/setup-php@9e72090525849c5e82e596468b86eb55e9cc5401 # v2
      with:
        php-version: ${{ inputs.php }}
        tools: composer:v2
        extensions: xmlwriter
        coverage: none
        ini-file: development
      env:
        fail-fast: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Get Composer cache directory
      id: composer-cache
      run: echo dir="$(composer config cache-files-dir)" >> "$GITHUB_OUTPUT"

    - name: Composer cache
      uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: composer-${{ inputs.php }}-${{ hashFiles('composer.json') }}

    - name: Install Composer dependencies
      run: | #shell
        if [ "${WP_VERSION}" == "latest" ]; then
          composer install --dev
        elif [ "${WP_VERSION}" == "nightly" ]; then
          composer require --dev --update-with-dependencies roots/wordpress-full="dev-main"
        elif [[ "${WP_VERSION}" =~ ^[0-9]\.[0-9]$ ]]; then
          composer require --dev --update-with-dependencies roots/wordpress-full="~${WP_VERSION}.0"
        else
          composer require --dev --update-with-dependencies roots/wordpress-full="${WP_VERSION}"
        fi
      env:
        WP_VERSION: ${{ inputs.wp }}

    - name: Setup node
      if: ${{ inputs.node }}
      uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
      with:
        node-version-file: '.nvmrc'
        cache: npm

    - name: Install node dependencies
      if: ${{ inputs.node }}
      run: npm ci

    - name: Run the build
      if: ${{ inputs.node }}
      run: npm run build

    - name: Start Docker environment
      run: composer exec tests-start -- --quiet-pull

    - name: Log running Docker containers
      run: docker ps -a

    - name: Run integration tests
      run: composer run test:integration
