# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Test Plugins
on:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: ${{ matrix.plugin }}
    if: github.event.pull_request.head.repo.full_name == 'johnbillion/plugin-infrastructure'
    env:
      BRANCH_REF: ${{ github.head_ref }}
    strategy:
      matrix:
        plugin:
          - extended-cpts
          - query-monitor
          - user-switching
          - wp-crontrol
      fail-fast: false
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: johnbillion/${{ matrix.plugin }}
          token: ${{ secrets.PLUGINS_PUSH_TOKEN }}

      - name: Update tests references
        run: |
          if [ -f .github/workflows/acceptance-tests.yml ]; then
            sed -i 's/reusable-acceptance-tests.yml@trunk/reusable-acceptance-tests.yml@${{ github.event.after }}/g' .github/workflows/acceptance-tests.yml
          fi
          if [ -f .github/workflows/coding-standards.yml ]; then
            sed -i 's/reusable-coding-standards.yml@trunk/reusable-coding-standards.yml@${{ github.event.after }}/g' .github/workflows/coding-standards.yml
          fi
          if [ -f .github/workflows/integration-tests.yml ]; then
            sed -i 's/reusable-integration-tests.yml@trunk/reusable-integration-tests.yml@${{ github.event.after }}/g' .github/workflows/integration-tests.yml
          fi

      - name: Check the changed files
        run: |
          git diff
          git status

      - name: Open PR
        uses: peter-evans/create-pull-request@v6
        id: cpr
        with:
          token: ${{ secrets.PLUGINS_PUSH_TOKEN }}
          commit-message: Update Plugin Infrastructure to ${{ github.event.after }}
          title: Update Plugin Infrastructure to ${{ env.BRANCH_REF }}
          body: |
            This PR updates [Plugin Infrastructure](https://github.com/johnbillion/plugin-infrastructure) to `${{ env.BRANCH_REF }}`.

            See ${{ github.event.pull_request._links.html.href }}.

            This is an automated PR created by [the Test Plugins workflow](https://github.com/johnbillion/plugin-infrastructure/actions/workflows/test-plugins.yml).
          branch: update-plugin-infrastructure
          draft: true

      - name: Set labels
        run: |
          gh pr edit ${{ github.event.number }} --add-label "pr:${{ matrix.plugin }}:${{ steps.cpr.outputs.pull-request-number }}"
        env:
            GH_TOKEN: ${{ github.token }}
