# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Tidy up
on:
  pull_request:
    types: [closed]

permissions:
  pull-requests: write

jobs:
  test:
    name: Close PRs
    if: github.event.pull_request.head.repo.full_name == 'johnbillion/plugin-infrastructure'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Close PRs
        uses: actions/github-script@v7
        with:
          script: | #js
            const pr = await github.pulls.get({
              owner: 'johnbillion',
              repo: 'plugin-infrastructure',
              pull_number: context.issue.number
            });
            const labels = pr.data.labels.map(label => label.name);

            for (const label of labels) {
              // label is in the format "pr:{repo}:{pr_number}", i.e. "pr:query-monitor:123"
              const [_, repo, pr_number] = label.split(':');

              if (!pr_number) {
                continue;
              }

              await github.pulls.update({
                owner: 'johnbillion',
                repo: repo,
                pull_number: pr_number,
                state: 'closed',
              });
            }
          github-token: ${{ secrets.PLUGINS_PUSH_TOKEN }}
