# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Tidy up
on:
  pull_request:
    types: [ closed ]

permissions: {}

jobs:
  close:
    name: Close PRs
    permissions: {}
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - name: Close PRs
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7
        with:
          retries: 2
          script: | #js
            const pr = await github.rest.pulls.get({
              owner: 'johnbillion',
              repo: 'plugin-infrastructure',
              pull_number: context.issue.number
            });
            const labels = pr.data.labels.map(label => label.name);

            for (const label of labels) {
              // label is in the format "pr:{repo}:{pr_number}", i.e. "pr:query-monitor:123"
              const [_, repo, pr_number] = label.split(':');

              if (!pr_number) {
                continue;
              }

              // Delete the label
              await github.rest.issues.deleteLabel({
                owner: 'johnbillion',
                repo: 'plugin-infrastructure',
                name: label,
              });

              // Close the plugin PR
              const pr = await github.rest.pulls.update({
                owner: 'johnbillion',
                repo: repo,
                pull_number: pr_number,
                state: 'closed',
              });

              // Delete the branch for the plugin PR
              await github.rest.git.deleteRef({
                owner: 'johnbillion',
                repo: repo,
                ref: `heads/${pr.data.head.ref}`,
              });
            }
          github-token: ${{ secrets.PLUGINS_PUSH_TOKEN }}
